version: 2

models:
  - name: fact_page_views
    description: contains all page view events from greenery
    columns: 
      - name: event_guid 
        description: UUID of each unique event on the platform
        tests:
          - unique
          - not_null
      - name: user_guid
        description: UUID of the user that this event is associated with
        tests:
          - unique
          - not_null
      - name: event_type
        description: Type of event (add_to_cart, checkout, page_view, package_shipped) in order workflow
        tests:
          - unique
          - not_null	       		

  - name: fact_user_sessions_product
    description: contains all page view events from greenery
    columns: 
      - name: product_guid 
        description: UUID of each unique product 
        tests:
          - unique
          - not_null
      - name: product_name
        description: name of product
        tests:
          - unique
          - not_null
      - name: conversion_rate_by_product
        description: summation of addtocart events / unique count of event sessions
        tests:
          - unique
          - not_null	     

      - name: prodcut_funnel
        description: contains product event total sessions and session flow/conversion rate
        columns: 
      - name: total_sessions
        description: total_sessions of the different web session events
        tests:
          - unique
          - not_null
      - name:  page_views
        description: unique not nulll page_views event type
        tests:
          - unique
          - not_null
      - name: add_to_carts
        description: unique not nulll add_to cart event type
        tests:
          - unique
          - not_null
      - name: checkouts
        description: unique not nulll checkout event type
        tests:
          - unique
          - not_null                    
      - name: page_view_flow
        description: landing to product page view conversion
        tests:
          - unique
          - not_null
      - name:  view_cart_flow 
        description: from page_view to add_to_cart flow conversion rate
        tests:
          - unique
          - not_null
      - name: cart_checkout_flow
        description: from add_to_cart to checkout flow conversion rate
        tests:
          - unique
          - not_null
      - name: page_view_checkout_flow
        description: from landing - product page views to checkout conversion rate
        tests:
          - unique
          - not_null 
